apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: multicluster-kueue-manager
spec:
  addOnMeta:
    displayName: multicluster-kueue-manager
    description: multicluster-kueue-manager
  supportedConfigs:
  - group: addon.open-cluster-management.io
    resource: addontemplates
  installStrategy:
    type: Placements
    placements:
    - name: {{ .Values.placement.name | default .Release.Name }}
      namespace: {{ .Release.Namespace }}
      configs:
      - name: kueue-addon-{{ .Chart.Version }}
        group: addon.open-cluster-management.io
        resource: addontemplates
