# The following workflow is to handle skipped but required jobs when only documentations is changed.
# Github doc: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: kueue-addon-pre

on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - 'kueue-addon/**'
    branches:
      - main

env:
  # Common versions
  GO_VERSION: '1.23'
  GO_REQUIRED_MIN_VERSION: ''

permissions:
  contents: read

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: verify
        run: make -C kueue-addon verify

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: build
        run: make -C kueue-addon build
