name: pre

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: pre-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-matrix:
    uses: ./.github/workflows/generate-matrix.yaml
    secrets: inherit

  call-test:
    name: test
    needs: generate-matrix
    if: needs.generate-matrix.outputs.matrix != ''
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    uses: ./.github/workflows/test.yml
    with:
      repo: ${{ matrix.repo }}
    secrets: inherit

  call-e2e:
    name: e2e
    needs: generate-matrix
    if: needs.generate-matrix.outputs.matrix != ''
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    uses: ./.github/workflows/e2e.yml
    with:
      repo: ${{ matrix.repo }}
      artifacts: ${{ fromJson(needs.generate-matrix.outputs.artifacts)[matrix.repo] }}
    secrets: inherit
